[package]
name = "endlessmeow"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
futures = "*"
rand = "0.8"
envy = "0.4"
serde = { version = "1", features = ["derive"]}

[profile.release]
lto = true
strip = true
codegen-units = 1
